# Bandizip压缩包文件删除工具配置文件

[bandizip]
# Bandizip可执行文件路径
executable = "D:\\1PRO\\Bandizip\\Bandizip\\bz.exe"

[delete_patterns]
# 默认要删除的文件模式
default = ["*.json", "*.convert","*.log",".yaml",".yml",".md"]

# 预定义的文件模式组合
[delete_patterns.presets]
# 临时文件
temp_files = ["*.tmp", "*.temp", "*.bak", "*.~*"]

# 日志文件
log_files = ["*.log", "*.txt"]

# 图片缓存
image_cache = ["*.thumb", "*.cache", "Thumbs.db"]

# 系统文件
system_files = ["desktop.ini", ".DS_Store", "*.lnk"]

# 开发文件
dev_files = ["*.pyc", "*.pyo", "__pycache__", "node_modules"]

[archive]
# 支持的压缩包格式
supported_extensions = ["*.zip", "*.rar", "*.7z", "*.tar", "*.gz", "*.bz2", "*.xz"]

# 搜索设置
recursive_search = true  # 是否递归搜索子目录
